builds:
- env:
  - CGO_ENABLED=0
  ignore:
    - goos: darwin
      goarch: 386
    - goos: linux
      goarch: 386
    - goos: linux
      goarch: arm
      goarm: 7
archives:
  - id: kubectl-iexec
    replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64
    name_template: "{{ .ProjectName }}_{{ .Tag }}_{{ .Os }}_{{ .Arch }}"
checksum:
  name_template: 'checksums.txt'
snapshot:
  name_template: "{{ .Tag }}-next"
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
